sudo: required #el sudo hace el arranque mas lento, hace falta??
language: java
services:
 - docker
before_install:
  - docker pull paberlo/gradlefinal
  - docker run -it -d --name build paberlo/gradlefinal
  - docker exec build git clone https://github.com/paberlo/partsUnlimitedLab.git home/gradle/repo/
script: 
  - docker exec build bash -c "cd home/gradle/repo/src/Clients/ && ./gradlew build"
  - docker exec build bash -c "cd home/gradle/repo/src/Backend/OrderService/ && ./gradlew build"