language: java
jdk: oraclejdk8
before_script:
  - chmod +x  $TRAVIS_BUILD_DIR/src/Backend/IntegrationService/gradlew
  - chmod +x  $TRAVIS_BUILD_DIR/src/Backend/OrderService/gradlew
  - chmod +x  $TRAVIS_BUILD_DIR/src/Clients/gradlew
script: 
 # - cd  $TRAVIS_BUILD_DIR/src/Backend/IntegrationService
 # - ./gradlew build
  - cd  $TRAVIS_BUILD_DIR/src/Backend/OrderService
  - ./gradlew build test
  #- cd  $TRAVIS_BUILD_DIR/src/Clients
  #- ./gradlew build

#build docker image and upload it to docker hub
#env credentials are created in travs-ci.or 
after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=partsunlimitedmrplab
  
  - cd $TRAVIS_BUILD_DIR
  
  - export TAG=ordering
  - docker build -t $REPO/$TAG docker/Ordering
  #- docker tag $REPO/$TAG paberlo/$REPO:$TAG
  #- docker push paberlo/$REPO:$TAG
  
 # - cd $TRAVIS_BUILD_DIR/src/Clients
 # - export TAG=web
 # - docker build -f Dockerfile -t $REPO/$TAG
 # - docker tag $REPO/$TAG paberlo/$REPO:$TAG
 # - docker push paberlo/$REPO:$TAG