sudo: required
language: java
services:
 - docker
before_install:
  - docker pull paberlo/gradlefinal
  - docker run -it -d --name build paberlo/gradlefinal
  - docker exec build git clone https://github.com/paberlo/partsUnlimitedLab.git /home/gradle/repo/
script: 
  - docker  exec build cd /home/gradle/repo/src/Clients/
  - docker exec build ./gradlew build
  - docker exec build cd /home/gradle/repo/src/Backend/OrderService/
  - docker exec build ./gradlew build